# my global config
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'nm626-monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alerts.yml"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  #  - job_name: 'node_exporter'
  #  scrape_interval: 60s
  #  static_configs:
  #  - targets: ['192.168.0.102:9100']

  - job_name: "luxws"
    scrape_interval: 60s
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: [ "192.168.0.102:8081" ]

  - job_name: "shelly"
    scrape_interval: 180s
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: [ "192.168.0.102:8082" ]

  - job_name: "mbmd"
    scrape_interval: 10s
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: [ "mbmd:7071" ]

#  ## gather the metrics of json_exporter application itself
#  - job_name: json_exporter
#    static_configs:
#      - targets:
#          ## Location of the json exporter's real <hostname>:<port>
#          - json_exporter:7979 # equivalent to "localhost:7979"

  ## gather the metrics from third party json sources, via the json exporter
  - job_name: jsonShelly1PM
    metrics_path: /probe
    params:
      module: [ shelly1pm ]
    static_configs:
      - targets:
          - http://192.168.0.147/rpc/Shelly.GetStatus # quooker/dish washer
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        ## Location of the json exporter's real <hostname>:<port>
        replacement: json_exporter:7979 # equivalent to "localhost:7979"

  - job_name: jsonShelly2PM
    metrics_path: /probe
    params:
      module: [ shelly2pm ]
    static_configs:
      - targets:
          - http://192.168.0.144/rpc/Shelly.GetStatus # shutter staircase
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        ## Location of the json exporter's real <hostname>:<port>
        replacement: json_exporter:7979 # equivalent to "localhost:7979"
