{
 "title": "PV Jahr",
 "tags": [ "PV" ],
 "time": { "from": "now/y", "to": "now/y" },
 "panels": [
  { "title": "Energie", "gridPos": { "h": 13, "w": 4, "x": 0, "y": 0 } },
  {
   "title": "Energie/30 Tage",
   "type": "timeseries",
   "description": "Einspeisevergütung und besonders die zugekauften Energiekosten sind hier Näherungen mit potentiell hoher Ungenauigkeit! (Integrale mit lückenhaften Daten)",
   "gridPos": { "h": 13, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Erzeugt von PV",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"value\")  / 3600 FROM \"pvPower\" WHERE $timeFilter AND value < 20000 GROUP BY time(30d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Zugekauft",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"value\") /3600 FROM \"gridPower\" WHERE $timeFilter AND value >= 0 GROUP BY time(30d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Haus",
     "query": "SELECT integral(\"value\")  / -3600 FROM \"homePower\" WHERE $timeFilter AND value < 20000 GROUP BY time(30d) fill(null)"
    },
    {
     "alias": "Auto",
     "query": "SELECT integral(\"value\")  / -3600 FROM \"chargePower\" WHERE $timeFilter AND value < 20000 GROUP BY time(30d) fill(null) "
    },
    {
     "alias": "Eingespeist",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"value\")  /3600 FROM \"gridPower\" WHERE \"value\" < 0 AND $timeFilter GROUP BY time(30d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Kennzahlen", "gridPos": { "h": 8, "w": 4, "x": 0, "y": 13 } },
  {
   "title": "Kennzahlen/30 Tage",
   "type": "timeseries",
   "description": "Autarkie und Eigenverbrauch sind hier Näherungen mit potentiell hoher Ungenauigkeit! (Integrale mit lückenhaften Daten)",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expression": "1-$zugekaufteEnergie/($energieAuto+$energieHaus)",
     "type": "math"
    },
    {
     "expression": "($energiePV - $energieEingespeist)/$energiePV",
     "type": "math"
    }
   ]
  },
  {
   "title": "Ertragsreichste Tage",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "PV Energie",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvPower",
     "query": "SELECT integral(\"value\")  / 3600 FROM \"pvPower\" WHERE  id='' AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "value::field", "operator": "<", "value": "10000" }
     ]
    }
   ]
  },
  {
   "title": "Höchste Einspeisungen",
   "type": "table",
   "description": " Einspeisevergütung ist hier eine Näherung mit potentiell hoher Ungenauigkeit! (Integrale mit lückenhaften Daten)",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Einspeisung",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gridPower",
     "query": "SELECT integral(\"value\")  / -3600 FROM \"gridPower\" WHERE (\"value\"::field < 0) AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / -3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "value::field", "operator": "<", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Höchste Hausverbräuche",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Hausverbrauch",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "homePower",
     "query": "SELECT integral(\"value\")  / 3600 FROM \"homePower\" WHERE (\"value\"::field < 10000) AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "value::field", "operator": "<", "value": "10000" }
     ]
    }
   ]
  },
  {
   "title": "Höchste Ladeverbräuche",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Geladen",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "chargePower",
     "query": "SELECT integral(\"value\")  / 3600 FROM \"chargePower\" WHERE (\"value\"::field < 10000) AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "value::field", "operator": "<", "value": "10000" }
     ]
    }
   ]
  },
  {
   "title": "Tägliche Energie Ø",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Erzeugt/Tag",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "batterySoc",
     "query": "SELECT integral(\"value\")  / 3600 FROM \"pvPower\" WHERE $timeFilter AND value < 20000 GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Verbraucht/Tag",
     "query": "SELECT integral(\"value\") /3600 FROM \"homePower\" WHERE $timeFilter AND value >= 0 GROUP BY time(1d) fill(null)"
    },
    {
     "alias": "Zugekauft/Tag",
     "query": "SELECT integral(\"value\") /3600 FROM \"gridPower\" WHERE $timeFilter AND value >= 0 GROUP BY time(1d) fill(null)"
    }
   ]
  },
  {
   "title": "Energie/Tag",
   "type": "timeseries",
   "description": "Zugekaufte Energiekosten ist hier eine Näherung mit potentiell hoher Ungenauigkeit! (Integrale mit lückenhaften Daten)",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Erzeugt",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "batterySoc",
     "query": "SELECT integral(\"value\")  / 3600 FROM \"pvPower\" WHERE $timeFilter AND value < 20000 GROUP BY time(1d) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Verbraucht",
     "query": "SELECT integral(\"value\") /3600 FROM \"homePower\" WHERE $timeFilter AND value <10000 GROUP BY time(1d) fill(null)"
    },
    {
     "alias": "Zugekauft",
     "query": "SELECT integral(\"value\") /3600 FROM \"gridPower\" WHERE $timeFilter AND value >= 0 GROUP BY time(1d) fill(null)"
    }
   ]
  },
  { "title": "Speicher", "gridPos": { "h": 9, "w": 4, "x": 0, "y": 41 } },
  {
   "title": "Speicher: Maximalwerte",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 41 },
   "targets": [
    {
     "alias": "Maximaler Batterie SOC/Tag",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "batterySoc",
     "query": "SELECT max(\"value\") FROM \"batterySoc\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speicher: Minimalwerte",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 41 },
   "targets": [
    {
     "alias": "Maximaler Batterie SOC/Tag",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "batterySoc",
     "query": "SELECT min(\"value\") FROM \"batterySoc\" WHERE $timeFilter AND value  > 0 GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  }
 ]
}