{
 "title": "PV Monat",
 "tags": [ "PV" ],
 "time": { "from": "now/M", "to": "now/M" },
 "panels": [
  { "title": "Energie", "gridPos": { "h": 14, "w": 4, "x": 0, "y": 0 } },
  {
   "title": "Energie",
   "type": "timeseries",
   "description": "Einspeisevergütung und besonders die zugekauften Energiekosten sind hier Näherungen mit potentiell hoher Ungenauigkeit! (Integrale mit lückenhaften Daten)",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "PV",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"value\")  / 3600 FROM \"pvPower\" WHERE $timeFilter AND id='' AND value>0 GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Zugekauft",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"value\") /3600 FROM \"gridPower\" WHERE $timeFilter AND value >= 0 GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Haus",
     "query": "SELECT integral(\"value\")  / -3600 FROM \"homePower\" WHERE $timeFilter GROUP BY time(1d) fill(null)"
    },
    {
     "alias": "Auto",
     "query": "SELECT integral(\"value\")  / -3600 FROM \"chargePower\" WHERE $timeFilter GROUP BY time(1d) fill(null) "
    },
    {
     "alias": "Eingespeist",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"value\")  /3600 FROM \"gridPower\" WHERE \"value\" < 0 AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Maximale PV Leistung pro Tag",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Maximale PV Leistung",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvPower",
     "query": "SELECT max(\"value\") FROM \"pvPower\" WHERE $timeFilter and id='' GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV Energie/kWp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kWh/kWp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$pvEnergy/9840", "type": "math" }
   ]
  },
  { "title": "Kennzahlen", "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 } },
  {
   "title": "Maximale PV Leistung pro Tag pro WR",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "SE10K",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvPower",
     "query": "SELECT max(\"value\") FROM \"pvPower\" WHERE $timeFilter and id='1' GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "SE17K",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvPower",
     "query": "SELECT max(\"value\") FROM \"pvPower\" WHERE $timeFilter and id='2' GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kennzahlen",
   "type": "timeseries",
   "description": "Autarkie und Eigenverbrauch sind hier Näherungen mit potentiell hoher Ungenauigkeit! (Integrale mit lückenhaften Daten)",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expression": "1-$zugekaufteEnergie/($energieAuto+$energieHaus)",
     "type": "math"
    },
    {
     "expression": "($energiePV - $energieEingespeist)/$energiePV",
     "type": "math"
    },
    {
     "alias": " ",
     "query": "SELECT min(\"value\") FROM \"sunElevation\" WHERE $timeFilter AND value = 0 GROUP BY time(1d) fill(null)"
    }
   ]
  },
  { "title": "Speicher", "gridPos": { "h": 7, "w": 4, "x": 0, "y": 24 } },
  {
   "title": "Hausspeicher Stände",
   "type": "timeseries",
   "description": "Speicher max und besonders Speicher min sind hier Näherungen mit potentiell hoher Ungenauigkeit! (Integrale mit lückenhaften Daten)",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 30 },
   "targets": [
    {
     "alias": "Speicher max",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "batterySoc",
     "query": "SELECT max(\"value\") FROM \"batterySoc\" WHERE $timeFilter and value <= 100 GROUP BY time(1d) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Speicher min",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "batterySoc",
     "query": "SELECT min(\"value\") FROM \"batterySoc\" WHERE $timeFilter and value <= 100 and value > 0 GROUP BY time(1d) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}