{
 "title": "PV Prometheus Today",
 "tags": [ "pv" ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "PV Production",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mbmd_measurement_energy_exported_total{device_name=\"se17kpv\"}[$__range])) \n+\nsum(increase(mbmd_measurement_energy_exported_total{device_name=\"se10kpv\"}[$__range])) ",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(increase(mbmd_measurement_energy_exported_total{device_name=\"se17kpv\"}[$__range])) ",
     "legendFormat": "SE17K (West)"
    },
    {
     "expr": "sum(increase(mbmd_measurement_energy_exported_total{device_name=\"se10kpv\"}[$__range])) ",
     "legendFormat": "SE10K (East)"
    },
    {
     "expr": "(sum(increase(mbmd_measurement_energy_exported_total{device_name=\"se17kpv\"}[$__range])) \n+\nsum(increase(mbmd_measurement_energy_exported_total{device_name=\"se10kpv\"}[$__range])) \n) / 27.72",
     "legendFormat": "kWh/kWp"
    }
   ]
  },
  {
   "title": "Export/Import Total TODAY",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time( max(mbmd_measurement_energy_exported_total{device_name=\"se10kgrid\",unit=\"kWh\"}>10)[$__range:10s] )   \n-\nmin_over_time( min(mbmd_measurement_energy_exported_total{device_name=\"se10kgrid\",unit=\"kWh\"}>10)[$__range:10s] )   \n",
     "legendFormat": "Export to Grid"
    },
    {
     "expr": "max_over_time( max(mbmd_measurement_energy_imported_total{device_name=\"se10kgrid\",unit=\"kWh\"}>10)[$__range:10s] )   \n-\nmin_over_time( min(mbmd_measurement_energy_imported_total{device_name=\"se10kgrid\",unit=\"kWh\"}>10)[$__range:10s] )   \n",
     "legendFormat": "Import from Grid"
    },
    {
     "expr": "(\n    max_over_time( max(mbmd_measurement_energy_exported_total{device_name=\"se17kpv\",unit=\"kWh\"}>0)[$__range:10s] )\n    -\n    min_over_time( min(mbmd_measurement_energy_exported_total{device_name=\"se17kpv\",unit=\"kWh\"}>0)[$__range:10s] )\n)\n+\n(\n    max_over_time( max(mbmd_measurement_energy_exported_total{device_name=\"se10kpv\",unit=\"kWh\"}>0)[$__range:10s] )\n    -\n    min_over_time( min(mbmd_measurement_energy_exported_total{device_name=\"se10kpv\",unit=\"kWh\"}>0)[$__range:10s] )\n)\n-\n(\n    max_over_time( max(mbmd_measurement_energy_exported_total{device_name=\"se10kgrid\",unit=\"kWh\"}>0)[$__range:10s] )\n    -\n    min_over_time( min(mbmd_measurement_energy_exported_total{device_name=\"se10kgrid\",unit=\"kWh\"}>0)[$__range:10s] )\n)\n",
     "legendFormat": "Solar Consumption"
    }
   ]
  },
  {
   "title": "PV Peak",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(mbmd_measurement_dc_power{device_name=\"se10kpv\",unit=\"W\"}[$__range]))",
     "legendFormat": "SE10K (East)"
    },
    {
     "expr": "sum(max_over_time(mbmd_measurement_dc_power{device_name=\"se17kpv\",unit=\"W\"}[$__range]))",
     "legendFormat": "SE17K (West)"
    }
   ]
  },
  {
   "title": "Power now",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mbmd_measurement_power{device_name=\"se17kpv\",unit=\"W\"}+ on() mbmd_measurement_power{device_name=\"se10kpv\",unit=\"W\"}- on()mbmd_measurement_power{device_name=\"se10kgrid\",unit=\"W\"}",
     "legendFormat": "Self consumption"
    },
    {
     "expr": "mbmd_measurement_power{device_name=\"se17kpv\",unit=\"W\"}+ on() mbmd_measurement_power{device_name=\"se10kpv\",unit=\"W\"}",
     "legendFormat": "Production"
    },
    {
     "expr": "-1*mbmd_measurement_power{device_name=\"se10kgrid\",unit=\"W\"}",
     "legendFormat": "Grid"
    }
   ]
  },
  {
   "title": "Operating Status",
   "type": "stat",
   "description": "Parameter   Value   Description\nI_STATUS_OFF        1         Off\nI_STATUS_SLEEPING   2     Sleeping (auto-shutdown) – Night mode\nI_STATUS_STARTING   3     Grid Monitoring/wake-up\nI_STATUS_MPPT       4     Inverter is ON and producing power\nI_STATUS_THROTTLED  5     Production (curtailed)\nI_STATUS_SHUTTING_DOWN 6     Shutting down\nI_STATUS_FAULT      7     Fault\nI_STATUS_STANDBY    8         Maintenance/setup\n",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mbmd_measurement_status{device_name=\"se10kpv\"}",
     "legendFormat": "{{device_name}}"
    },
    {
     "expr": "mbmd_measurement_status{device_name=\"se17kpv\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Energy Meter Watt/Power",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "mbmd_measurement_power{device_name=\"se10kgrid\",unit=\"W\"}",
     "legendFormat": "Grid Feed-In"
    },
    {
     "expr": "mbmd_measurement_power{device_name=\"se17kpv\",unit=\"W\"}+ on() mbmd_measurement_power{device_name=\"se10kpv\",unit=\"W\"}",
     "legendFormat": "PV Production Total"
    },
    {
     "expr": "(mbmd_measurement_power{device_name=\"se17kpv\",unit=\"W\"}+ on() mbmd_measurement_power{device_name=\"se10kpv\",unit=\"W\"})\n- \non()mbmd_measurement_power{device_name=\"se10kgrid\",unit=\"W\"}",
     "legendFormat": "Self consumption"
    },
    {
     "target": [
      "sun_altitude",
      "sunrise",
      "sunset"
     ]
    }
   ]
  },
  {
   "title": "Energy Generated last 7 days",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum( increase(mbmd_measurement_energy_exported_total{device_name=\"se10kpv\",unit=\"kWh\"}[1d] offset -1d ) )  ",
     "legendFormat": "SE10K"
    },
    {
     "expr": "sum( increase(mbmd_measurement_energy_exported_total{device_name=\"se17kpv\",unit=\"kWh\"}[1d] offset -1d ) )  ",
     "legendFormat": "SE17K"
    },
    {
     "expr": "(sum( increase(mbmd_measurement_energy_exported_total{device_name=\"se17kpv\",unit=\"kWh\"}[1d] offset -1d ) )  )\n+\n(sum( increase(mbmd_measurement_energy_exported_total{device_name=\"se10kpv\",unit=\"kWh\"}[1d] offset -1d ) )  )",
     "legendFormat": "SExxK Total"
    }
   ]
  },
  {
   "title": "Energy Imported last 7 days",
   "type": "barchart",
   "description": "> 900 means that 900 is the kWh count of already imported energy ... because the counter does not start from 0",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "max_over_time( max(mbmd_measurement_energy_imported_total{device_name=\"se10kgrid\",unit=\"kWh\"}>10)[1d:10s]offset -1d )   \n-\nmin_over_time( min(mbmd_measurement_energy_imported_total{device_name=\"se10kgrid\",unit=\"kWh\"}>10)[1d:10s]offset -1d )   \n",
     "legendFormat": "SE10K"
    }
   ]
  },
  {
   "title": "Energy Exported last 7 days",
   "type": "barchart",
   "description": "> 2984 means that 2984 is the kWh count of already exported energy ... because the counter does not start from 0",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "max_over_time( max(mbmd_measurement_energy_exported_total{device_name=\"se10kgrid\",unit=\"kWh\"}>10)[1d:10s]offset -1d )   \n-\nmin_over_time( min(mbmd_measurement_energy_exported_total{device_name=\"se10kgrid\",unit=\"kWh\"}>10)[1d:10s]offset -1d )   \n",
     "legendFormat": "SE10K"
    }
   ]
  },
  {
   "title": "DC Power/Watt",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "mbmd_measurement_dc_power{device_name=\"se10kpv\",unit=\"W\"}>0",
     "legendFormat": "{{device_name}}"
    },
    {
     "expr": "mbmd_measurement_dc_power{device_name=\"se17kpv\",unit=\"W\"}>0",
     "legendFormat": "{{device_name}}"
    },
    {
     "expr": "( \nmbmd_measurement_dc_power{device_name=\"se17kpv\",unit=\"W\"} + on() mbmd_measurement_dc_power{device_name=\"se10kpv\",unit=\"W\"}\n) > 0",
     "legendFormat": "SE10+SE17"
    }
   ]
  },
  {
   "title": "Energy Meter AC Watt/Power per Inverter",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "mbmd_measurement_power{device_name=\"se10kpv\",unit=\"W\"}>0",
     "legendFormat": "SE10K (East)"
    },
    {
     "expr": "mbmd_measurement_power{device_name=\"se17kpv\",unit=\"W\"}>0",
     "legendFormat": "SE17K (West)"
    },
    {
     "expr": "mbmd_measurement_power{device_name=\"se10kgrid\",unit=\"W\"}>0",
     "legendFormat": "To Grid (after self consumption)"
    }
   ]
  },
  {
   "title": "AC Volt Grid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "mbmd_measurement_l1_voltage{device_name=\"se10kgrid\"}",
     "legendFormat": "AC L1"
    },
    {
     "expr": "mbmd_measurement_l2_voltage{device_name=\"se10kgrid\"}",
     "legendFormat": "AC L2"
    },
    {
     "expr": "mbmd_measurement_l3_voltage{device_name=\"se10kgrid\"}",
     "legendFormat": "AC L3"
    }
   ]
  },
  {
   "title": "DC Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "mbmd_measurement_dc_voltage{device_name=\"se10kpv\",unit=\"V\"}",
     "legendFormat": "{{device_name}}"
    },
    {
     "expr": "mbmd_measurement_dc_voltage{device_name=\"se17kpv\",unit=\"V\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "mbmd_measurement_frequency{device_name=\"se10kgrid\"}",
     "legendFormat": "{{device_name}}"
    },
    {
     "expr": "mbmd_measurement_frequency{device_name=\"se10kpv\"}",
     "legendFormat": "{{device_name}}"
    },
    {
     "expr": "mbmd_measurement_frequency{device_name=\"se17kpv\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Apparent Power",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mbmd_measurement_l1_apparent_power{device_name=\"se10kgrid\"}",
     "legendFormat": "Grid L1"
    },
    {
     "expr": "mbmd_measurement_l2_apparent_power{device_name=\"se10kgrid\"}",
     "legendFormat": "Grid L2"
    },
    {
     "expr": "mbmd_measurement_l3_apparent_power{device_name=\"se10kgrid\"}",
     "legendFormat": "Grid L3"
    }
   ]
  },
  {
   "title": "Temperatures Heat Sink",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "mbmd_measurement_heat_sink_temperature{device_name=\"se10kpv\",unit=\"°C\"}",
     "legendFormat": "{{device_name}}"
    },
    {
     "expr": "mbmd_measurement_heat_sink_temperature{device_name=\"se17kpv\",unit=\"°C\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Reactive Power in Voltamperes (reactive)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "voltampreact" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mbmd_measurement_l1_reactive_power{device_name=\"se10kgrid\"}",
     "legendFormat": "Grid L1"
    },
    {
     "expr": "mbmd_measurement_l2_reactive_power{device_name=\"se10kgrid\"}",
     "legendFormat": "Grid L2"
    },
    {
     "expr": "mbmd_measurement_l3_reactive_power{device_name=\"se10kgrid\"}",
     "legendFormat": "Grid L3"
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mbmd_measurement_l1_voltage{device_name=\"se10kgrid\"}",
     "legendFormat": "Grid L1"
    },
    {
     "expr": "mbmd_measurement_l2_voltage{device_name=\"se10kgrid\"}",
     "legendFormat": "Grid L2"
    },
    {
     "expr": "mbmd_measurement_l3_voltage{device_name=\"se10kgrid\"}",
     "legendFormat": "Grid L3"
    }
   ]
  },
  {
   "title": "Current (A)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mbmd_measurement_l1_current{device_name=\"se10kgrid\"}",
     "legendFormat": "Grid L1"
    },
    {
     "expr": "mbmd_measurement_l2_current{device_name=\"se10kgrid\"}",
     "legendFormat": "Grid L2"
    },
    {
     "expr": "mbmd_measurement_l3_current{device_name=\"se10kgrid\"}",
     "legendFormat": "Grid L3"
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mbmd_measurement_l1_voltage{device_name=\"se10kpv\"}",
     "legendFormat": "SE10K L1"
    },
    {
     "expr": "mbmd_measurement_l2_voltage{device_name=\"se10kpv\"}",
     "legendFormat": "SE10K L2"
    },
    {
     "expr": "mbmd_measurement_l3_voltage{device_name=\"se10kpv\"}",
     "legendFormat": "SE10K L3"
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mbmd_measurement_l1_voltage{device_name=\"se17kpv\"}",
     "legendFormat": "SE17K L1"
    },
    {
     "expr": "mbmd_measurement_l2_voltage{device_name=\"se17kpv\"}",
     "legendFormat": "SE17K L2"
    },
    {
     "expr": "mbmd_measurement_l3_voltage{device_name=\"se17kpv\"}",
     "legendFormat": "SE17K L3"
    }
   ]
  },
  {
   "title": "Current (A)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mbmd_measurement_l1_current{device_name=\"se10kpv\"}",
     "legendFormat": "SE10K L1"
    },
    {
     "expr": "mbmd_measurement_l2_current{device_name=\"se10kpv\"}",
     "legendFormat": "SE10K L2"
    },
    {
     "expr": "mbmd_measurement_l3_current{device_name=\"se10kpv\"}",
     "legendFormat": "SE10K L3"
    }
   ]
  },
  {
   "title": "Current (A)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mbmd_measurement_l1_current{device_name=\"se17kpv\"}",
     "legendFormat": "SE17K L1"
    },
    {
     "expr": "mbmd_measurement_l2_current{device_name=\"se17kpv\"}",
     "legendFormat": "SE17K L2"
    },
    {
     "expr": "mbmd_measurement_l3_current{device_name=\"se17kpv\"}",
     "legendFormat": "SE17K L3"
    }
   ]
  },
  {
   "title": "Reactive Power in Voltamperes (reactive)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "voltampreact" } },
   "targets": [
    {
     "expr": "mbmd_measurement_reactive_power{device_name=\"se10kpv\"}",
     "legendFormat": "{{device_name}}"
    },
    {
     "expr": "mbmd_measurement_reactive_power{device_name=\"se17kpv\"}",
     "legendFormat": "{{device_name}}"
    },
    {
     "expr": "mbmd_measurement_reactive_power{device_name=\"se10kgrid\"}",
     "legendFormat": "Grid"
    }
   ]
  },
  {
   "title": "Operating State Long Term",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
   "targets": [
    {
     "expr": "mbmd_measurement_status{device_name=\"se10kpv\"}",
     "legendFormat": "{{device_name}}"
    },
    {
     "expr": "mbmd_measurement_status{device_name=\"se17kpv\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Inverter Status Vendor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
   "targets": [
    {
     "expr": "mbmd_measurement_status_vendor{device_name=\"se10kpv\"}",
     "legendFormat": "{{device_name}}"
    },
    {
     "expr": "mbmd_measurement_status_vendor{device_name=\"se17kpv\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  }
 ]
}